### ISSUE TITLE
running errors

### ISSUE THREAD

**Issue by houze-liu** [HareeshBahuleyan/tf-var-attention#1]
my tensorflow version is 1.12.0 and got somes errors when running your code
https://github.com/HareeshBahuleyan/tf-var-attention/blob/3e74c43721deae86a36a609f089f5b5644b989b5/ved_varAttn/varAttention_decoder/attention_wrapper.py#L1145
 https://github.com/HareeshBahuleyan/tf-var-attention/blob/3e74c43721deae86a36a609f089f5b5644b989b5/ved_varAttn/varAttention_decoder/basic_decoder.py#L40
`rnn_cell_impl._like_rnncell()` seems no longer exists. Instead, we got:
https://github.com/tensorflow/tensorflow/blob/d63e3ea9a26fc049c654a966d0ebc56bc2747729/tensorflow/python/ops/rnn_cell_impl.py#L65
(`assert_like_rnncell()` won't allow passing for `DropoutWrapper` type, which is the type of `cell` above when running your code)

Another error:
https://github.com/HareeshBahuleyan/tf-var-attention/blob/3e74c43721deae86a36a609f089f5b5644b989b5/ved_varAttn/varAttention_decoder/basic_decoder.py#L72
 `compute_output_shape` works instead of `_compute_output_shape`; didn't check source code.
I'm not very sure if my problem relating to 'pylint', but as far as I know `# pylint: disable=protected-access ` is just used to disable warning messages.

**Comment by HareeshBahuleyan** [comment]
Hi @houze-liu 
The code in this repository was originally written in tensorflow==1.3.0 (please check README for other package version requirements)
I haven't tested it for the latest version of tensorflow.  There could be some compatibility issues such as the ones you have encountered. 

Could you please test it on tensorflow 1.3.0 instead?

Hareesh
