### ISSUE TITLE
Number of LSTM layers

### ISSUE THREAD

**Issue by qlwang25** [HareeshBahuleyan/tf-var-attention#2]
https://github.com/HareeshBahuleyan/tf-var-attention/blob/3e74c43721deae86a36a609f089f5b5644b989b5/ved_detAttn/ved_detAttn.py#L117-L134

if num_layers = 3,  so there are one input layer, one output layer and three hiddens layer.
And the output of the first layer is the input of the second layer.
Can these codes do that ? 
For each layer lstm, it has the same input  **self.enc_embed_input**  .

**Comment by HareeshBahuleyan** [comment]
Hi @qlwang25,
Yes, you are right - this code does not actually implement a "stacked" LSTM. Thanks for pointing it out.

But this can be easily achieved initializing an array of LSTM cells (of size _n_layers_) and looping through the array, feeding the output of layer _i_ to layer _i+1_. 

You may refer to the following for details: https://stackoverflow.com/questions/46189318/how-to-use-multilayered-bidirectional-lstm-in-tensorflow

Or if you are working with a more recent version of TF, you can call [`stack_bidirectional_dynamic_rnn`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/stack_bidirectional_dynamic_rnn)

**Comment by qlwang25** [comment]
Thanks @HareeshBahuleyan for links, 
i get your points.
